BEGIN;

-- Ensure required CMU building references exist
INSERT INTO cmu_buildings (name, code, address, latitude, longitude, zone)
VALUES
  ('Posner Hall', 'POS', 'Posner Hall, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4447, -79.9438, 'Central Campus'),
  ('Forbes Beeler Apartments', 'FBA', 'Forbes & Beeler Apartments, 5121 Beeler St, Pittsburgh, PA 15213', 40.4419, -79.9380, 'East Campus'),
  ('Newell-Simon Hall', 'NSH', 'Newell-Simon Hall, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4435, -79.9451, 'Central Campus'),
  ('Scaife Hall', 'SCF', 'Scaife Hall, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4432, -79.9465, 'Central Campus'),
  ('Scott Hall', 'SCH', 'Scott Hall, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4446, -79.9448, 'Central Campus'),
  ('College of Fine Arts', 'CFA', 'College of Fine Arts, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4417, -79.9418, 'Central Campus'),
  ('Legacy Plaza', 'LPZ', 'Legacy Plaza, 5000 Forbes Ave, Pittsburgh, PA 15213', 40.4448, -79.9442, 'Central Campus'),
  ('Highmark Center for Health, Wellness and Athletics', 'HCWA', 'Highmark Center for Health, Wellness and Athletics, 4665 Forbes Ave, Pittsburgh, PA 15213', 40.4406, -79.9457, 'Central Campus')
ON CONFLICT (name) DO UPDATE
SET
  code = EXCLUDED.code,
  address = EXCLUDED.address,
  latitude = EXCLUDED.latitude,
  longitude = EXCLUDED.longitude,
  zone = EXCLUDED.zone,
  is_active = TRUE;

-- Refresh restaurant catalog to match current CMU dining concepts
DELETE FROM menu_items;
DELETE FROM menu_categories;
DELETE FROM restaurants;

INSERT INTO restaurants (
  name,
  description,
  cuisine_type,
  building_id,
  address,
  latitude,
  longitude,
  phone,
  email,
  website_url,
  logo_url,
  cover_image_url,
  opening_hours,
  minimum_order,
  base_delivery_fee,
  accepts_dining_dollars,
  average_prep_time,
  is_active
)
VALUES
  ('Au Bon Pain at Skibo Cafe', 'Coffee, espresso, soups, sandwiches, salads, grab-and-go items, parfaits, fruit, and snacks.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"07:00","close":"21:00"},"tuesday":{"open":"07:00","close":"21:00"},"wednesday":{"open":"07:00","close":"21:00"},"thursday":{"open":"07:00","close":"21:00"},"friday":{"open":"07:00","close":"21:00"},"saturday":{"open":"07:00","close":"21:00"},"sunday":{"open":"07:00","close":"21:00"}}', 0.00, 0.00, TRUE, 10, TRUE),
  ('Capital Grains - Rohr Commons', 'Student-run grain and salad bowl concept.', 'Healthy', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, TRUE, 15, TRUE),
  ('Ciao Bella', 'Customizable pasta plates.', 'Italian', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:00"},"tuesday":{"open":"10:30","close":"20:00"},"wednesday":{"open":"10:30","close":"20:00"},"thursday":{"open":"10:30","close":"20:00"},"friday":{"open":"10:30","close":"20:00"},"saturday":{"open":"10:30","close":"20:00"},"sunday":{"open":"10:30","close":"20:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Crisp and Crust', 'Fresh, made-to-order salads, flatbreads, and roll-ups.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:00"},"tuesday":{"open":"10:30","close":"20:00"},"wednesday":{"open":"10:30","close":"20:00"},"thursday":{"open":"10:30","close":"20:00"},"friday":{"open":"10:30","close":"20:00"},"saturday":{"open":"10:30","close":"20:00"},"sunday":{"open":"10:30","close":"20:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('De Fer Coffee & Tea at Resnik', 'Locally-roasted specialty coffee, tea, and scratch-made food.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"07:00","close":"20:00"},"tuesday":{"open":"07:00","close":"20:00"},"wednesday":{"open":"07:00","close":"20:00"},"thursday":{"open":"07:00","close":"20:00"},"friday":{"open":"07:00","close":"20:00"},"saturday":{"open":"07:00","close":"20:00"},"sunday":{"open":"07:00","close":"20:00"}}', 0.00, 0.00, TRUE, 10, TRUE),
  ('E.A.T. (Evenings at Tepper) - Rohr Commons', 'Evening dinner options at Tepper available through Grubhub.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, NULL, 0.00, 0.00, TRUE, 20, TRUE),
  ('The Edge Cafe & Market', 'Vaad-certified kosher bagels, pizza, bourekas, and more.', 'Kosher', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"23:59"},"tuesday":{"open":"11:00","close":"23:59"},"wednesday":{"open":"11:00","close":"23:59"},"thursday":{"open":"11:00","close":"23:59"},"friday":{"open":"11:00","close":"23:59"},"saturday":{"open":"11:00","close":"23:59"},"sunday":{"open":"11:00","close":"23:59"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Entropy+', 'On-campus convenience store with snacks, grab-and-go meals, coffee, and more.', 'Convenience', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"07:00","close":"22:00"},"tuesday":{"open":"07:00","close":"22:00"},"wednesday":{"open":"07:00","close":"22:00"},"thursday":{"open":"07:00","close":"22:00"},"friday":{"open":"07:00","close":"22:00"},"saturday":{"open":"07:00","close":"22:00"},"sunday":{"open":"07:00","close":"22:00"}}', 0.00, 0.00, TRUE, 5, TRUE),
  ('The Exchange', 'Deli and breakfast sandwiches, daily hot entrees, and grab-and-go options.', 'Deli', (SELECT id FROM cmu_buildings WHERE name = 'Posner Hall'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Posner Hall'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Posner Hall'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Posner Hall'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"19:00"},"tuesday":{"open":"08:00","close":"19:00"},"wednesday":{"open":"08:00","close":"19:00"},"thursday":{"open":"08:00","close":"19:00"},"friday":{"open":"08:00","close":"19:00"},"saturday":{"open":"08:00","close":"19:00"},"sunday":{"open":"08:00","close":"19:00"}}', 0.00, 0.00, TRUE, 12, TRUE),
  ('Fire and Stone', 'Grilled steaks, fish, and wings.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"16:30","close":"21:00"},"tuesday":{"open":"16:30","close":"21:00"},"wednesday":{"open":"16:30","close":"21:00"},"thursday":{"open":"16:30","close":"21:00"},"friday":{"open":"16:30","close":"21:00"},"saturday":{"open":"16:30","close":"21:00"},"sunday":{"open":"16:30","close":"21:00"}}', 0.00, 0.00, TRUE, 20, TRUE),
  ('Forbes Avenue Subs - Rohr Commons', 'Made-to-order deli-style subs and wraps with vegan options.', 'Sandwiches', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"16:00"},"tuesday":{"open":"11:00","close":"16:00"},"wednesday":{"open":"11:00","close":"16:00"},"thursday":{"open":"11:00","close":"16:00"},"friday":{"open":"11:00","close":"16:00"},"saturday":{"open":"11:00","close":"16:00"},"sunday":{"open":"11:00","close":"16:00"}}', 0.00, 0.00, TRUE, 12, TRUE),
  ('El Gallo De Oro', 'Mexican cuisine with burritos, bowls, tacos, quesadillas, and salads.', 'Mexican', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"21:00"},"tuesday":{"open":"10:30","close":"21:00"},"wednesday":{"open":"10:30","close":"21:00"},"thursday":{"open":"10:30","close":"21:00"},"friday":{"open":"10:30","close":"21:00"},"saturday":{"open":"10:30","close":"21:00"},"sunday":{"open":"10:30","close":"21:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Hunan Express', 'Asian cuisine featuring rice bowls, boba tea, and smoothies.', 'Asian', (SELECT id FROM cmu_buildings WHERE name = 'Newell-Simon Hall'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Newell-Simon Hall'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Newell-Simon Hall'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Newell-Simon Hall'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:00"},"tuesday":{"open":"10:30","close":"20:00"},"wednesday":{"open":"10:30","close":"20:00"},"thursday":{"open":"10:30","close":"20:00"},"friday":{"open":"10:30","close":"20:00"},"saturday":{"open":"10:30","close":"20:00"},"sunday":{"open":"10:30","close":"20:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Rohr Cafe - La Prima', 'Italian-style coffee bar inside Gates Hillman Centers.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'Gates Hillman Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Gates Hillman Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Gates Hillman Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Gates Hillman Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"07:30","close":"18:00"},"tuesday":{"open":"07:30","close":"18:00"},"wednesday":{"open":"07:30","close":"18:00"},"thursday":{"open":"07:30","close":"18:00"},"friday":{"open":"07:30","close":"18:00"},"saturday":{"open":"07:30","close":"18:00"},"sunday":{"open":"07:30","close":"18:00"}}', 0.00, 0.00, TRUE, 8, TRUE),
  ('Millie''s Coffee ''n'' Creamery - Rohr Commons', 'Sustainably sourced coffee, ice cream, and vegan gelato.', 'Dessert', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"22:00"},"tuesday":{"open":"08:00","close":"22:00"},"wednesday":{"open":"08:00","close":"22:00"},"thursday":{"open":"08:00","close":"22:00"},"friday":{"open":"08:00","close":"22:00"},"saturday":{"open":"08:00","close":"22:00"},"sunday":{"open":"08:00","close":"22:00"}}', 0.00, 0.00, TRUE, 10, TRUE),
  ('Nourish', 'Grubhub-only safe foods for those with dietary restrictions.', 'Healthy', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"18:00"},"tuesday":{"open":"10:30","close":"18:00"},"wednesday":{"open":"10:30","close":"18:00"},"thursday":{"open":"10:30","close":"18:00"},"friday":{"open":"10:30","close":"18:00"},"saturday":{"open":"10:30","close":"18:00"},"sunday":{"open":"10:30","close":"18:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Ola Ola', 'Hand-crafted signature sandwiches and smash burgers.', 'Sandwiches', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"21:00"},"tuesday":{"open":"10:30","close":"21:00"},"wednesday":{"open":"10:30","close":"21:00"},"thursday":{"open":"10:30","close":"21:00"},"friday":{"open":"10:30","close":"21:00"},"saturday":{"open":"10:30","close":"21:00"},"sunday":{"open":"10:30","close":"21:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('La Prima Espresso', 'Italian-style coffee, espresso, pastries, and grab-and-go items.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'Wean Hall'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Wean Hall'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Wean Hall'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Wean Hall'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"18:00"},"tuesday":{"open":"08:00","close":"18:00"},"wednesday":{"open":"08:00","close":"18:00"},"thursday":{"open":"08:00","close":"18:00"},"friday":{"open":"08:00","close":"18:00"},"saturday":{"open":"08:00","close":"18:00"},"sunday":{"open":"08:00","close":"18:00"}}', 0.00, 0.00, TRUE, 8, TRUE),
  ('Redhawk Coffee', 'Local coffee roaster serving specialty drinks, baked goods, and grab-and-go food.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'Scaife Hall'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Scaife Hall'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Scaife Hall'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Scaife Hall'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"17:00"},"tuesday":{"open":"08:00","close":"17:00"},"wednesday":{"open":"08:00","close":"17:00"},"thursday":{"open":"08:00","close":"17:00"},"friday":{"open":"08:00","close":"17:00"},"saturday":{"open":"08:00","close":"17:00"},"sunday":{"open":"08:00","close":"17:00"}}', 0.00, 0.00, TRUE, 8, TRUE),
  ('Revolution Noodle', 'Customizable Malatang noodle bowls from the owners of Hunan Express.', 'Asian', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:00"},"tuesday":{"open":"10:30","close":"20:00"},"wednesday":{"open":"10:30","close":"20:00"},"thursday":{"open":"10:30","close":"20:00"},"friday":{"open":"10:30","close":"20:00"},"saturday":{"open":"10:30","close":"20:00"},"sunday":{"open":"10:30","close":"20:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Rohr Commons - Tepper Eatery', 'Salad bar, homemade soup, and grab ''n'' go options.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"20:00"},"tuesday":{"open":"11:00","close":"20:00"},"wednesday":{"open":"11:00","close":"20:00"},"thursday":{"open":"11:00","close":"20:00"},"friday":{"open":"11:00","close":"20:00"},"saturday":{"open":"11:00","close":"20:00"},"sunday":{"open":"11:00","close":"20:00"}}', 0.00, 0.00, TRUE, 12, TRUE),
  ('Salem''s Hot Bar', 'Ready-to-eat delicacies from the hot bar inside Scotty''s Market.', 'Mediterranean', (SELECT id FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"22:00"},"tuesday":{"open":"10:30","close":"22:00"},"wednesday":{"open":"10:30","close":"22:00"},"thursday":{"open":"10:30","close":"22:00"},"friday":{"open":"10:30","close":"22:00"},"saturday":{"open":"10:30","close":"22:00"},"sunday":{"open":"10:30","close":"22:00"}}', 0.00, 0.00, TRUE, 12, TRUE),
  ('Schatz Dining Room', 'All-you-care-to-eat residential dining hall inside the Cohon Center.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Cohon University Center'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Cohon University Center'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Cohon University Center'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Cohon University Center'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"07:30","close":"20:30"},"tuesday":{"open":"07:30","close":"20:30"},"wednesday":{"open":"07:30","close":"20:30"},"thursday":{"open":"07:30","close":"20:30"},"friday":{"open":"07:30","close":"20:30"},"saturday":{"open":"07:30","close":"20:30"},"sunday":{"open":"07:30","close":"20:30"}}', 0.00, 0.00, TRUE, 20, TRUE),
  ('The Grill at Scotty''s', 'Freshly grilled entrees all day in Scotty''s Market.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"23:45"},"tuesday":{"open":"08:00","close":"23:45"},"wednesday":{"open":"08:00","close":"23:45"},"thursday":{"open":"08:00","close":"23:45"},"friday":{"open":"08:00","close":"23:45"},"saturday":{"open":"08:00","close":"23:45"},"sunday":{"open":"08:00","close":"23:45"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Scotty''s Market by Salem''s', 'International and conventional groceries with savory grilled meats and hot meals.', 'Mediterranean', (SELECT id FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Forbes Beeler Apartments'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"23:59"},"tuesday":{"open":"08:00","close":"23:59"},"wednesday":{"open":"08:00","close":"23:59"},"thursday":{"open":"08:00","close":"23:59"},"friday":{"open":"08:00","close":"23:59"},"saturday":{"open":"08:00","close":"23:59"},"sunday":{"open":"08:00","close":"23:59"}}', 0.00, 0.00, TRUE, 10, TRUE),
  ('Shake Smart', 'Protein-packed smoothies, acai bowls, and more.', 'Smoothies', (SELECT id FROM cmu_buildings WHERE name = 'Highmark Center for Health, Wellness and Athletics'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Highmark Center for Health, Wellness and Athletics'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Highmark Center for Health, Wellness and Athletics'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Highmark Center for Health, Wellness and Athletics'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:00"},"tuesday":{"open":"10:30","close":"20:00"},"wednesday":{"open":"10:30","close":"20:00"},"thursday":{"open":"10:30","close":"20:00"},"friday":{"open":"10:30","close":"20:00"},"saturday":{"open":"10:30","close":"20:00"},"sunday":{"open":"10:30","close":"20:00"}}', 0.00, 0.00, TRUE, 8, TRUE),
  ('Stack''d Dessert Bar', 'Made-to-order milkshakes and sweet treats.', 'Dessert', (SELECT id FROM cmu_buildings WHERE name = 'Morewood Gardens'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Morewood Gardens'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Morewood Gardens'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Morewood Gardens'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"23:59"},"tuesday":{"open":"11:00","close":"23:59"},"wednesday":{"open":"11:00","close":"23:59"},"thursday":{"open":"11:00","close":"23:59"},"friday":{"open":"11:00","close":"23:59"},"saturday":{"open":"11:00","close":"23:59"},"sunday":{"open":"11:00","close":"23:59"}}', 0.00, 0.00, TRUE, 8, TRUE),
  ('Stack''d Underground', 'Smash burgers, Nashville-style chicken, and gourmet grilled cheese.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Morewood Gardens'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Morewood Gardens'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Morewood Gardens'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Morewood Gardens'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"23:59"},"tuesday":{"open":"11:00","close":"23:59"},"wednesday":{"open":"11:00","close":"23:59"},"thursday":{"open":"11:00","close":"23:59"},"friday":{"open":"11:00","close":"23:59"},"saturday":{"open":"11:00","close":"23:59"},"sunday":{"open":"11:00","close":"23:59"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Stephanie''s - Market C', '24-hour micro market with sandwiches, wraps, salads, snacks, and coffee.', 'Convenience', (SELECT id FROM cmu_buildings WHERE name = 'Mellon Institute'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Mellon Institute'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Mellon Institute'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Mellon Institute'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"00:00","close":"23:59"},"tuesday":{"open":"00:00","close":"23:59"},"wednesday":{"open":"00:00","close":"23:59"},"thursday":{"open":"00:00","close":"23:59"},"friday":{"open":"00:00","close":"23:59"},"saturday":{"open":"00:00","close":"23:59"},"sunday":{"open":"00:00","close":"23:59"}}', 0.00, 0.00, TRUE, 5, TRUE),
  ('Sweet Plantain', 'Cuban-inspired pop-up menu available through Grubhub.', 'Caribbean', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"16:30","close":"21:00"},"tuesday":{"open":"16:30","close":"21:00"},"wednesday":{"open":"16:30","close":"21:00"},"thursday":{"open":"16:30","close":"21:00"},"friday":{"open":"16:30","close":"21:00"},"saturday":{"open":"16:30","close":"21:00"},"sunday":{"open":"16:30","close":"21:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Tahini', 'Fresh Mediterranean fare with certified kosher cuisine.', 'Mediterranean', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"21:00"},"tuesday":{"open":"11:00","close":"21:00"},"wednesday":{"open":"11:00","close":"21:00"},"thursday":{"open":"11:00","close":"21:00"},"friday":{"open":"11:00","close":"21:00"},"saturday":{"open":"11:00","close":"21:00"},"sunday":{"open":"11:00","close":"21:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Tartan Express Food Truck', 'Food truck serving chicken tenders, fries, sandwiches, and egg rolls.', 'American', (SELECT id FROM cmu_buildings WHERE name = 'Legacy Plaza'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Legacy Plaza'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Legacy Plaza'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Legacy Plaza'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"10:30","close":"20:30"},"tuesday":{"open":"10:30","close":"20:30"},"wednesday":{"open":"10:30","close":"20:30"},"thursday":{"open":"10:30","close":"20:30"},"friday":{"open":"10:30","close":"20:30"},"saturday":{"open":"10:30","close":"20:30"},"sunday":{"open":"10:30","close":"20:30"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Taste of India', 'Vibrant Indian cuisine with a mix of classic dishes.', 'Indian', (SELECT id FROM cmu_buildings WHERE name = 'Resnik House'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Resnik House'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Resnik House'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Resnik House'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"21:00"},"tuesday":{"open":"11:00","close":"21:00"},"wednesday":{"open":"11:00","close":"21:00"},"thursday":{"open":"11:00","close":"21:00"},"friday":{"open":"11:00","close":"21:00"},"saturday":{"open":"11:00","close":"21:00"},"sunday":{"open":"11:00","close":"21:00"}}', 0.00, 0.00, TRUE, 20, TRUE),
  ('Tepper Taqueria', 'Mexican-style street tacos, burritos, bowls, and nachos.', 'Mexican', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"16:00"},"tuesday":{"open":"11:00","close":"16:00"},"wednesday":{"open":"11:00","close":"16:00"},"thursday":{"open":"11:00","close":"16:00"},"friday":{"open":"11:00","close":"16:00"},"saturday":{"open":"11:00","close":"16:00"},"sunday":{"open":"11:00","close":"16:00"}}', 0.00, 0.00, TRUE, 12, TRUE),
  ('Tepper Taqueria Express', 'Grab-and-go tacos, empanadas, and more.', 'Mexican', (SELECT id FROM cmu_buildings WHERE name = 'Tepper Quad'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Tepper Quad'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Tepper Quad'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Tepper Quad'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"16:00"},"tuesday":{"open":"11:00","close":"16:00"},"wednesday":{"open":"11:00","close":"16:00"},"thursday":{"open":"11:00","close":"16:00"},"friday":{"open":"11:00","close":"16:00"},"saturday":{"open":"11:00","close":"16:00"},"sunday":{"open":"11:00","close":"16:00"}}', 0.00, 0.00, TRUE, 10, TRUE),
  ('Wild Blue Sushi - Ruge Atrium', 'Fresh prepared sushi, hot rice bowls, bubble tea, and coffee.', 'Japanese', (SELECT id FROM cmu_buildings WHERE name = 'Scott Hall'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'Scott Hall'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'Scott Hall'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'Scott Hall'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"11:00","close":"18:00"},"tuesday":{"open":"11:00","close":"18:00"},"wednesday":{"open":"11:00","close":"18:00"},"thursday":{"open":"11:00","close":"18:00"},"friday":{"open":"11:00","close":"18:00"},"saturday":{"open":"11:00","close":"18:00"},"sunday":{"open":"11:00","close":"18:00"}}', 0.00, 0.00, TRUE, 15, TRUE),
  ('Zebra Lounge', 'Coffee and espresso drinks, pastries, sushi, bagels, and pizza.', 'Cafe', (SELECT id FROM cmu_buildings WHERE name = 'College of Fine Arts'), COALESCE((SELECT address FROM cmu_buildings WHERE name = 'College of Fine Arts'), '5000 Forbes Ave, Pittsburgh, PA 15213'), COALESCE((SELECT latitude FROM cmu_buildings WHERE name = 'College of Fine Arts'), 40.4443), COALESCE((SELECT longitude FROM cmu_buildings WHERE name = 'College of Fine Arts'), -79.9427), NULL, NULL, NULL, NULL, NULL, '{"monday":{"open":"08:00","close":"16:00"},"tuesday":{"open":"08:00","close":"16:00"},"wednesday":{"open":"08:00","close":"16:00"},"thursday":{"open":"08:00","close":"16:00"},"friday":{"open":"08:00","close":"16:00"},"saturday":{"open":"08:00","close":"16:00"},"sunday":{"open":"08:00","close":"16:00"}}', 0.00, 0.00, TRUE, 8, TRUE)
;

COMMIT;
